### PR TITLE
Update For Directions

### PR DESCRIPTION
**Pull request by obito1406**
Hi I noticed that Direction was a bit out of date so i created and update some classes in order to be able to retrieve the new information provided by the Google Directions  API.

The changes are:
-Update to DirectionLeg and DirectionStep(only add some atributtes and delete "maneuver" since its not used anymore)
-Add the class required for the new "transit_details"

Im new to this so if ive done anything wrong just comment and ill do it again. Even some advice for the pull, because I dont know if I do it the way its supposed to be done.
Thanks

### CODE REVIEW

**Comment by ericnewton76** [comment]
So we can't just delete the property, anybody linking to it would get missing property exceptions.

Instead we must first mark the property as Obsolete with false for generate error, then on next major version, mark with Obsolete(true), then next major version we can remove the property.

**Comment by obito1406** [comment]
Ok didnt know about that sorry. Ive changed it adding it again but obsolete as you said.
 Is there anything else to do?

**Comment by ericnewton76** [comment]
Since the manuever property is obsolete, did you remove any output of manuever? (I didnt check)   This is just so that its consistent that its obsolete (and probably not even really considered by the underlying service now)

**Comment by ericnewton76** [comment]
Hey, this actually doesnt build: (This means I need to fix the AppVeyor build)

Direction\DirectionLeg.cs(33,17): error CS0246: The type or namespace name 'Time' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\gmaps-api-net\src\Google.Maps\Google.Maps.csproj]
Direction\DirectionLeg.cs(36,17): error CS0246: The type or namespace name 'Time' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\gmaps-api-net\src\Google.Maps\Google.Maps.csproj]
Direction\DirectionStep.cs(30,10): error CS0246: The type or namespace name 'DirectionTransitDetails' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\gmaps-api-net\src\Google.Maps\Google.Maps.csproj]

**Comment by ericnewton76** [comment]
I think I see the problem, you forgot to checkin the file additions to the csproj

**Comment by obito1406** [comment]
Hi, Ive realised a few days ago that the maneuver its not obsolete as I though at first. My mistake was due to maneuver always being null but it seems that its sometimes used as I see later. So you may want to change it. Im sorry for that. By the way ive been testing the other fields or JsonAtributes and it seems to work just so you know. Ty for the merge 

    El Miércoles 17 de agosto de 2016 16:39, Eric Newton <notifications@github.com> escribió:
 

 Merged #54.—

**Comment by ericnewton76** [comment]
Well in that case, go ahead and undo the change... can't really revert
since i've done some project level source code reformatting

**Pull request merged**
