### PR TITLE
Implemented snap to roads functionality from Roads API

### PR DESCRIPTION
**Pull request by LukLed**
Added RoadsService with "Snap to Roads" functionality. Roads API is wider, but I needed this functionality. Unfortunately API key provided in project doesn't allow this (403 forbidden). I am not sure why. I can write tests, but I need working key and confirmation that this has chance to land in main repository.

### CODE REVIEW

**Comment by normanhh3** [comment]
In case it is relevant I just used the code from the fork in a reporting project I needed and it worked just fine. Test passed in my book!

**Comment by LukLed** [comment]
@normanhh3 Thank you. I am using this code with my own production Google API key, but I am not sure how to approach it in tests.

**Comment by richardthombs** [comment]
The tests are using my own API key and I've probably not enabled the Roads API, I'll check the portal in a bit and see if there's something I can enable...

**Comment by richardthombs** [comment]
Hi @LukLed , thanks for the PR. I've updated the API key used by the tests so that the Roads API is enabled, so it should be possible to write a test or two now :)

Cheers,

R.

**Comment by LukLed** [comment]
I've added few tests. Functionality is simple, so there is only one test to check if it really works. The rest is to check correct URI generation.

**Pull request merged**
