### PR TITLE
Add optional proxy for requests. Introduce Proxy.AssignAllServices()

### PR DESCRIPTION
**Pull request by sphinxy**
Just an optional proxy support, used same way as GoogleSigned()

### CODE REVIEW

**Comment by ericnewton76** [comment]
I want to merge this pull request in, but the secondary commit, with returning true for all certificates is a big no-no.

**Comment by ericnewton76** [comment]
actually i just found this stackoverflow article about builtin proxy support

http://stackoverflow.com/questions/1938990/c-sharp-connecting-through-proxy

**Comment by mieliespoor** [comment]
We have been using the web.config to be able to go through the proxy. I most cases it works. We are having issues with our proxy, so the cases it doesn't work is because of the proxy itself.

I do however believe that this library should really worry about handling of the proxy, so I don't really see the true value of this PR.

**Comment by ericnewton76** [comment]
By your last msg, did you want to close this PR without merge?

**Comment by ericnewton76** [comment]
I'm closing this pull request, since there's two issues:
- original author questions need after finding out proxy can be configured through web.config
- commit added that causes major security violation with always returning true for Certificate validation.

**Pull request closed without merging**
