### PR TITLE
Remove the Sensor parameter from all requests as Google no longer requires it

### PR DESCRIPTION
**Pull request by richardthombs**
Removing the validation around the Sensor parameter revealed flaws in two tests:

1. `DirectionRequestTests.GetUrl_no_Origin_set` only used to pass because it wasn't setting the Sensor parameter. The GetUrl method doesn't check to see whether Origin is set.
1. `GeocodingRequestTests.GetUrl_no_Address_set` fails for the same reason - it doesn't set the Sensor parameter and the GetUrl method being tested doesn't check to see whether Address is set.

Personally I think we might as well remove both of these tests and any remaining verification code - having our own verification of requests adds needless complexity.

### CODE REVIEW

**Comment by ericnewton76** [comment]
oh snap, double work! lol

**Comment by ericnewton76** [comment]
so i overlaid your changes onto mine.  if this works out, we'll close this PR and commit the other one.

**Comment by ericnewton76** [comment]
After thinking about it, I think it's better to leave the Sensor property on the various classes to prevent compile errors, and deprecate the property with warnings.

**Comment by richardthombs** [comment]
I can totally see the point in keeping the Sensor property and marking it obsolete, but I don't like the idea of continuing to add it to the query string when it's used, even though Google doesn't want it anymore - why add that complexity to the code when nobody needs it?

**Comment by richardthombs** [comment]
Hey @ericnewton76 , I've updated my patch so that all requests have a `Sensor` property again, but it is marked as obsolete.

All internal usage of `Sensor` is still removed though, I really think this is the right approach.

**Pull request merged**
