### PR TITLE
vNext

### PR DESCRIPTION
**Pull request by richardthombs**
Features:
1. Per-service `GoogleSigned` instances (fcdade3)
1. Support for async/await via `GetResponseAsync()` methods (dd7492a)
1. Updated `StaticMapService` API (a12f94f)
1. `System.Drawing.Color` and `System.Drawing.Size` have been replaced with our own `MapColor` and `MapSize` structs so we can remove System.Drawing as a dependency, which is necessary in order to be able to produce a build for .NET Standard 1.x.

### CODE REVIEW

**Comment by ericnewton76** [comment]
Ok, do we think its time for v1.0 release yet?

**Comment by richardthombs** [comment]
I've got a vs2017 and .NET Standard 1.3 branch that we could put in first?

**Comment by ericnewton76** [comment]
shoot, we should've had this as a separate branch for vNext for a bit... i'll have to revert these commits

**Comment by richardthombs** [comment]
How come?

R.
--

**Pull request merged**
